CamOn-FE/Controllers/BuyPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObjects;
using Microsoft.AspNetCore.Identity;

namespace CamOn_FE.Controllers
{
    public class BuyPackagesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<Account> _userManager;

        public BuyPackagesController(UserManager<Account> userManager, AppDbContext context)
        {
            _userManager = userManager; 
            _context = context;
        }

        // GET: Packages
        public async Task<IActionResult> Index()
        {
              return _context.Packages != null ? 
                          View(await _context.Packages.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Packages'  is null.");
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Packages == null)
            {
                return NotFound();
            }

            var package = await _context.Packages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (package == null)
            {
                return NotFound();
            }
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("Index","Home");
            }
            ViewData["userEmail"] = currentUser.Email;

            return View(package);
        }

    }
}

CamOn-FE/Controllers/CamerasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace CamOn_FE.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CamerasController : Controller
    {
        private readonly AppDbContext _context;

        public CamerasController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Cameras
        public async Task<IActionResult> Index()
        {
              return _context.Cameras != null ? 
                          View(await _context.Cameras.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Cameras'  is null.");
        }

        // GET: Cameras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cameras == null)
            {
                return NotFound();
            }

            var camera = await _context.Cameras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (camera == null)
            {
                return NotFound();
            }

            return View(camera);
        }

        // GET: Cameras/Create
        public IActionResult Create()
        {
            ViewData["AccountId"] = new SelectList(_context.Accounts, "Id", "Id");
            return View();
        }

        // POST: Cameras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,IpAddress,AccountId,Id")] Camera camera)
        {
            if (ModelState.IsValid)
            {
                _context.Add(camera);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(camera);
        }

        // GET: Cameras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cameras == null)
            {
                return NotFound();
            }

            var camera = await _context.Cameras.FindAsync(id);
            if (camera == null)
            {
                return NotFound();
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "Id", "Id");
            return View(camera);
        }

        // POST: Cameras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,IpAddress,AccountId,Id")] Camera camera)
        {
            if (id != camera.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(camera);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CameraExists(camera.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(camera);
        }

        // GET: Cameras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cameras == null)
            {
                return NotFound();
            }

            var camera = await _context.Cameras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (camera == null)
            {
                return NotFound();
            }

            return View(camera);
        }

        // POST: Cameras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cameras == null)
            {
                return Problem("Entity set 'AppDbContext.Cameras'  is null.");
            }
            var camera = await _context.Cameras.FindAsync(id);
            if (camera != null)
            {
                _context.Cameras.Remove(camera);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CameraExists(int id)
        {
          return (_context.Cameras?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CamOn-FE/Controllers/PackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace CamOn_FE.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PackagesController : Controller
    {
        private readonly AppDbContext _context;

        public PackagesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Packages
        public async Task<IActionResult> Index()
        {
              return _context.Packages != null ? 
                          View(await _context.Packages.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Packages'  is null.");
        }

        // GET: Packages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Packages == null)
            {
                return NotFound();
            }

            var package = await _context.Packages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (package == null)
            {
                return NotFound();
            }

            return View(package);
        }

        // GET: Packages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Packages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,MonthValue,CameraValue,Price,Id")] Package package)
        {
            if (ModelState.IsValid)
            {
                _context.Add(package);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(package);
        }

        // GET: Packages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Packages == null)
            {
                return NotFound();
            }

            var package = await _context.Packages.FindAsync(id);
            if (package == null)
            {
                return NotFound();
            }
            return View(package);
        }

        // POST: Packages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,MonthValue,CameraValue,Price,Id")] Package package)
        {
            if (id != package.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(package);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PackageExists(package.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(package);
        }

        // GET: Packages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Packages == null)
            {
                return NotFound();
            }

            var package = await _context.Packages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (package == null)
            {
                return NotFound();
            }

            return View(package);
        }

        // POST: Packages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Packages == null)
            {
                return Problem("Entity set 'AppDbContext.Packages'  is null.");
            }
            var package = await _context.Packages.FindAsync(id);
            if (package != null)
            {
                _context.Packages.Remove(package);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PackageExists(int id)
        {
          return (_context.Packages?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CamOn-FE/Controllers/UsersController.cs
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace CamOn_FE.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<Account> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<Account> userManager, RoleManager<IdentityRole> roleManager,AppDbContext context)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = _context.Users.ToList();
            var accountRoles = users.Select(u => new AccountRole
            {
                Id = u.Id,
                UserName = u.UserName,
                RoleName = _userManager.GetRolesAsync(u).Result.FirstOrDefault()
            }).ToList();

            ViewBag.Roles = _roleManager.Roles.ToList();

            return View(accountRoles);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserRole(string userId, string newRole)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            if (user == null)
            {
                return Json(new { success = false, message = "User not found." });
            }

            var roles = await _userManager.GetRolesAsync(user);
            var removedResult = await _userManager.RemoveFromRolesAsync(user, roles.ToArray());
            if (!removedResult.Succeeded)
            {
                return Json(new { success = false, message = "Error removing user from existing roles." });
            }

            var addResult = await _userManager.AddToRoleAsync(user, newRole);
            if (addResult.Succeeded)
            {
                return Json(new { success = true, message = "User role updated successfully." });
            }
            else
            {
                return Json(new { success = false, message = "Error adding user to new role." });
            }
        }
    }
}
public class AccountRole : Account
{
    public string? RoleName { get; set; }
}

CamOn-FE/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<style>
    .sidebar {
        background-color: white;
        border: 2px solid orange;
        height: 100vh; /* Full height */
        padding-top: 20px;
        display: flex;
        flex-direction: column;
        align-items: center;
        position: fixed; /* Make sidebar fixed */
        top: 0;
        left: 0;
        width: 250px; /* Fixed width for sidebar */
        overflow-y: auto; /* Enable scrolling within the sidebar if needed */
    }

    .content {
        margin-left: 250px; /* Left margin to account for sidebar width */
        padding: 20px;
    }

    .navbar-brand {
        display: flex;
        justify-content: center;
        width: 100%;
        padding: 10px;
        border-bottom: 2px solid orange;
    }

        .navbar-brand img {
            width: 80%; /* Adjust this value to make the logo smaller */
            height: auto; /* Maintain aspect ratio */
        }

    #sidebar .nav-link {
        color: #000;
        padding: 10px 15px;
    }

        #sidebar .nav-link:hover {
            background-color: #f8f9fa;
            color: #007bff;
        }

</style>
<body>


    <div class="container-fluid">
        <div class="row">
            <div class="sidebar">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/webLogo.jpg" alt="Logo">
                </a>
                <nav class="navbar navbar-expand-md navbar-light">
                    <div class="collapse navbar-collapse" id="sidebar">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Admin" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Admin" asp-action="AssignPackages">Assign Packages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Users" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Cameras" asp-action="Index">Camera</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Packages" asp-action="Index">Package</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="UserPackages" asp-action="Index">User Packages</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="content col-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CamOn-FE/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<BusinessObjects.Account> SignInManager
@inject UserManager<BusinessObjects.Account> UserManager
@{
    var user = UserManager.GetUserAsync(User).Result;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CamOn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

    <!-- Favicon -->
    <link rel="icon" href="/webLogo.jpg" type="image/jpeg" sizes="75x75">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/webLogo.jpg" alt="Logo" width="75" height="75">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="height: 75px;">
                    <ul class="navbar-nav flex-grow-1" style="height:100%">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" onclick="highlightLink(this)">Home</a>
                        </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserCamera" asp-action="Index" onclick="highlightLink(this)">Camera</a>
                        </li>
                    }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BuyPackages" asp-action="Index" onclick="highlightLink(this)">Packages</a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; CamOn
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>


    <script>
        // Get the current URL path
        var path = window.location.pathname;

        // Get all nav items
        var navItems = document.querySelectorAll('.nav-item');

        // Loop through each nav item
        navItems.forEach(function (navItem) {
            // Get the link inside the nav item
            var navLink = navItem.querySelector('.nav-link');

            // Check if the href attribute matches the current URL path
            if (navLink.getAttribute('href') === path) {
                // Add the 'active' class to the matching nav item
                navItem.classList.add('active');
            }
        });

    </script>

    <style>
        .nav-item {
            height:100%;
            display: flex;
            align-items: center;
            font-weight: bold;
        }
        .nav-item.active {
            background-color: orange;
        }
        .nav-item.active .nav-link {
            color: white !important; /* Add !important to override Bootstrap styles */
        }
    </style>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>